documents = {
    0:'''At Scale You Will Hit Every Performance Issue I used to think I knew a bit about performance scalability and how to keep things trucking when you hit large amounts of data Truth is I know diddly squat on the subject since the most I have ever done is read about how its done To understand how I came about realising this you need some background''',
    1:'''Richard Stallman to visit Australia Im not usually one to promote events and the like unless I feel there is a genuine benefit to be had by attending but this is one stands out Richard M Stallman the guru of Free Software is coming Down Under to hold a talk You can read about him here Open Source Celebrity to visit Australia''',
    2:'''MySQL Backups Done Easily One thing that comes up a lot on sites like Stackoverflow and the like is how to backup MySQL databases The first answer is usually use mysqldump This is all fine and good till you start to want to dump multiple databases You can do this all in one like using the all databases option however this makes restoring a single database an issue since you have to parse out the parts you want which can be a pain''',
    3:'''Why You Shouldnt roll your own CAPTCHA At a TechEd I attended a few years ago I was watching a presentation about Security presented by Rocky Heckman read his blog its quite good In it he was talking about security algorithms The part that really stuck with me went like this''',
    4:'''The Great Benefit of Test Driven Development Nobody Talks About The feeling of productivity because you are writing lots of code Think about that for a moment Ask any developer who wants to develop why they became a developer One of the first things that comes up is I enjoy writing code This is one of the things that I personally enjoy doing Writing code any code especially when its solving my current problem makes me feel productive It makes me feel like Im getting somewhere Its empowering''',
    5:'''Setting up GIT to use a Subversion SVN style workflow Moving from Subversion SVN to GIT can be a little confusing at first I think the biggest thing I noticed was that GIT doesnt have a specific workflow you have to pick your own Personally I wanted to stick to my Subversion like work-flow with a central server which all my machines would pull and push too Since it took a while to set up I thought I would throw up a blog post on how to do it''',
    6:'''Why CAPTCHA Never Use Numbers 0 1 5 7 Interestingly this sort of question pops up a lot in my referring search term stats Why CAPTCHAs never use the numbers 0 1 5 7 Its a relativity simple question with a reasonably simple answer Its because each of the above numbers are easy to confuse with a letter See the below''',
    
    7: '''Understanding Distributed Systems: A Primer Distributed systems are the backbone of modern applications, yet they come with their own set of challenges. From network partitions to eventual consistency, understanding these concepts is crucial for building scalable and resilient systems. This document aims to provide a high-level overview of the key concepts and trade-offs involved in distributed systems.''',
    
    8: '''The Evolution of Containerization: From Chroot to Kubernetes Containerization has revolutionized the way we deploy and manage applications. Starting with simple chroot environments, the technology has evolved into sophisticated platforms like Docker and Kubernetes. This document explores the history and evolution of containerization, highlighting key milestones and their impact on the industry.''',
    
    9: '''The Importance of Code Reviews in Software Development Code reviews are an essential part of the software development process. They help catch bugs early, improve code quality, and foster knowledge sharing among team members. This document discusses the benefits of code reviews, best practices, and common pitfalls to avoid.''',
    
    10: '''A Deep Dive into GraphQL: Pros and Cons GraphQL has gained popularity as a flexible and efficient alternative to REST APIs. However, it’s not without its drawbacks. This document provides an in-depth look at the advantages and disadvantages of using GraphQL, along with practical tips for implementing it in your projects.''',
    
    11: '''The Rise of Edge Computing: What You Need to Know Edge computing is transforming the way data is processed and delivered. By bringing computation closer to the data source, it reduces latency and bandwidth usage. This document explores the key concepts behind edge computing, its benefits, and potential use cases.''',
    
    12: '''Debugging Microservices: Challenges and Strategies Debugging microservices can be a daunting task due to their distributed nature. This document outlines the common challenges faced when debugging microservices and provides strategies to effectively identify and resolve issues in a microservices architecture.''',
    
    13: '''The Role of AI in Modern Cybersecurity Artificial Intelligence is playing an increasingly important role in cybersecurity. From threat detection to automated response, AI is helping organizations stay ahead of cyber threats. This document examines the various ways AI is being used in cybersecurity and the potential future developments in this field.''',
    
    14: '''The Pros and Cons of Serverless Architecture Serverless architecture has gained traction as a way to build scalable and cost-effective applications. However, it’s not a one-size-fits-all solution. This document discusses the advantages and disadvantages of serverless architecture, along with scenarios where it makes the most sense.''',
    
    15: '''The Impact of Quantum Computing on Cryptography Quantum computing has the potential to revolutionize many fields, including cryptography. This document explores the implications of quantum computing on current cryptographic practices and discusses the development of quantum-resistant algorithms.''',
    
    16: '''The Future of DevOps: Trends and Predictions DevOps continues to evolve as new tools and practices emerge. This document looks at the latest trends in DevOps, including the rise of GitOps, the increasing importance of security in the DevOps pipeline, and the growing adoption of AI and machine learning in DevOps practices.''',
    
    17: '''The Challenges of Data Privacy in the Age of Big Data As data collection grows, so do the challenges of ensuring data privacy. This document examines the complexities of data privacy in the context of big data, discussing regulatory requirements, technical solutions, and the ethical considerations involved.''',
    
    18: '''The Role of Blockchain in Supply Chain Management Blockchain technology is being explored as a way to enhance transparency and efficiency in supply chain management. This document delves into the potential benefits of using blockchain in supply chains, including improved traceability, reduced fraud, and increased trust among stakeholders.''',
     19: '''Welcome to TechInsights - Your Source for the Latest in Technology News Stay updated with the latest trends, breakthroughs, and innovations in the tech world. From AI to quantum computing, we cover it all. Visit our blog for in-depth articles, tutorials, and expert opinions. Don't forget to subscribe to our newsletter for weekly updates!''',
    
    20: '''About Us - GreenEarth Organics At GreenEarth Organics, we are passionate about providing high-quality organic products. Our mission is to promote sustainable living by offering eco-friendly and ethically sourced goods. Learn more about our story, values, and the farmers we work with to bring you the best organic products.''',
    
    21: '''Product Page - SmartHome Pro Thermostat The SmartHome Pro Thermostat is your ultimate solution for energy-efficient home heating and cooling. With advanced AI algorithms, it learns your schedule and preferences to optimize temperature settings. Features include remote control via smartphone, energy usage reports, and compatibility with voice assistants like Alexa and Google Home. Order now and enjoy a 10% discount!''',
    
    22: '''Contact Us - BlueSky Travel Agency Planning your next vacation? BlueSky Travel Agency is here to help! Whether you're looking for a tropical getaway, a cultural tour, or an adventure trip, our expert agents are ready to assist you. Reach out to us via phone, email, or visit our office. We look forward to making your travel dreams come true!''',
    
    23: '''Home - FitnessPlus Gym Join FitnessPlus Gym and take the first step towards a healthier lifestyle. Our state-of-the-art facilities, experienced trainers, and wide range of classes cater to all fitness levels. From yoga to high-intensity interval training, we have something for everyone. Sign up today and get your first month free!''',
    
    24: '''Blog - Culinary Delights by Chef Maria Discover the art of cooking with Chef Maria. Our blog features a variety of recipes, cooking tips, and culinary techniques. Whether you're a beginner or a seasoned chef, you'll find inspiration and guidance to create delicious meals at home. Don't miss our weekly video tutorials and exclusive interviews with top chefs.''',
    
    25: '''Services - WebCraft Solutions WebCraft Solutions offers a full range of web development and digital marketing services. From custom website design to SEO and social media management, we help businesses establish a strong online presence. Our team of experts is dedicated to delivering tailored solutions that drive results. Contact us today for a free consultation!''',
    
    26: '''FAQ - PetCare Veterinary Clinic At PetCare Veterinary Clinic, we understand that you have questions about your pet's health and well-being. Our FAQ section covers common topics such as vaccination schedules, dietary recommendations, and emergency care. If you don't find the answers you're looking for, feel free to reach out to our friendly staff.''',
    
    27: '''Events - Community Arts Center The Community Arts Center is proud to host a variety of events throughout the year. From art exhibitions to live performances, there's always something exciting happening. Check out our calendar for upcoming events and ticket information. Join us in celebrating the arts and supporting local talent!''',
    
    28: '''Privacy Policy - SecureBank At SecureBank, we are committed to protecting your privacy. Our Privacy Policy outlines how we collect, use, and safeguard your personal information. We adhere to strict data protection regulations and employ advanced security measures to ensure your data is safe. Read our full Privacy Policy to learn more about your rights and our practices.''',
    
    29: '''Testimonials - HappyPaws Pet Grooming Don't just take our word for it - hear from our satisfied customers! At HappyPaws Pet Grooming, we take pride in providing top-notch grooming services for your furry friends. Our testimonials section features reviews from pet owners who have experienced our exceptional care and attention to detail. Book an appointment today and see why we're the best in town!''',
    
    30: '''Careers - InnovateTech Join the InnovateTech team and be part of a company that's shaping the future of technology. We offer a dynamic work environment, competitive benefits, and opportunities for professional growth. Explore our current job openings and apply today to take the next step in your career. InnovateTech - where innovation meets talent!''',
    
    31: '''Terms of Service - StreamNow Streaming Platform Welcome to StreamNow, your go-to platform for streaming movies, TV shows, and live events. Our Terms of Service outline the rules and guidelines for using our platform. By accessing StreamNow, you agree to comply with these terms. Please read them carefully to understand your rights and responsibilities as a user.''',
    
    32: '''Gallery - Nature's Beauty Photography Explore the stunning work of Nature's Beauty Photography. Our gallery showcases breathtaking landscapes, wildlife, and natural wonders from around the world. Each photograph tells a story and captures the essence of the natural world. Visit our gallery to experience the beauty of nature through the lens of our talented photographers.''',
    
    33: '''Membership - EliteFitness Club Become a member of EliteFitness Club and unlock exclusive benefits. Enjoy unlimited access to our premium facilities, personalized training programs, and member-only events. Our membership plans are designed to fit your lifestyle and fitness goals. Join today and take your fitness journey to the next level!''',
}